#!/bin/bash
#SBATCH --job-name=llama3-ft
#SBATCH --nodes=1
#SBATCH --gres=gpu:4
#SBATCH --cpus-per-task=8
#SBATCH --mem=0
#SBATCH --time=00:30:00
#SBATCH --output=llama3_%j.out


# Standard output and error:
#SBATCH -o ./jobfiles/out.%j
#SBATCH -e ./jobfiles/err.%j

module load anaconda/2024
eval "$(conda shell.bash hook)"
conda activate llama3-lora

torchrun --nnodes 1 --nproc_per_node 4 \
  finetune.py